### ISSUE TITLE
[1.5.2] Some delicious bugs 

### ISSUE THREAD

**Issue by Pyromanc3r** [VintageModsReforged/AdvancedMachines#1] opened 2024-11-24 10:40 UTC
Hi again. I decided to see what this mod is. At the first test I found a few bugs.
1. All machines show missing texture if you toggle the recipe page.
![2024-11-24_11 58 40](https://github.com/user-attachments/assets/b0f8dd7d-4c5e-4cbd-af8b-04c686422753)
![2024-11-24_11 58 45](https://github.com/user-attachments/assets/d108975f-6561-4153-8eec-987aec930df8)

2. `Energy storage upgrade` (ic2) do not affect the machines in this mod. Energy buffer is not increased.
![2024-11-24_12 28 50](https://github.com/user-attachments/assets/26100a73-a497-4e96-b08f-98f247ec0b31)
![2024-11-24_12 28 52](https://github.com/user-attachments/assets/b4444645-acb6-4cf5-a0ff-9ce0f3d252a7)
![2024-11-24_13 27 11](https://github.com/user-attachments/assets/d5bcc996-d006-4733-96b7-d0df1b2840b1)

3. Induction furnace MKII + Cobblestone generator upgrade.
Generating cobblestone without energy:
![2024-11-24_12 00 52](https://github.com/user-attachments/assets/6e6c9e6b-b78e-4264-b405-c3b45438e673)

3a. `Cobblestone generator upgrade` has no recipe.

4. Unnamed recipe. If you create this item... game will crash and you cannot enter the world.
LV-transformer + Complex electronic circuit + EV transformer
![2024-11-24_11 49 13](https://github.com/user-attachments/assets/7605ba5c-1c29-48dd-896c-cba4bb01c454)

5. `Charged electrolyzer`. Electrolyzed water cell doesn't give energy back when the energy store is empty. 
![2024-11-24_13 07 23](https://github.com/user-attachments/assets/2ea6c7ec-f296-4145-87dc-91fa171f5297)

how to test: put the full MFE (ic2) next to Electrolyzer (ic2), place water cell inside, it will charge. 
![2024-11-24_13 12 10](https://github.com/user-attachments/assets/61e66da4-ec4b-4de4-81be-29aa805a7451)

Now empty the MFE. Electrolyzed water cells via Electrolyzer will charge the MFE. 
Now try to do the same with Adv. machines addon.

Actually the problem with `Charged electrolyzer` is that it only accepts El. water cells through the left slot. Not how it works in basic IC2, where from the right slot the capsules are returned to the left slot.

**Comment by CrossVas** [comment] 2024-11-24 12:51
What version is this?
Mod version?
Testing instance modlist?

I guess it's `1.5.2`. I'll take a look at it and return with a detailed response later.

**Comment by CrossVas** [comment] 2024-11-24 13:43
1. Fixed. A wrong path was provided when porting from `1.4.7`. We actually don't need duplicate recipes providers for AdvMachines, these are added as usage providers only.

2. The advanced machines are counterparts of Induction Furnace, which has no upgrade support, 2 additional slots were added for the Redstone Inverter and Cobblestone Upgrade. Support for other upgrades is undecided yet.

3. Cobblestone Upgrade works without energy. That's intended.

3a. Fixed. Cobblestone Upgrade recipe uses OreDict values, which weren't present. Now the OreDict values are added, and the recipe is fixed.

4. `Unnamed` and with `missing textures` because the object is actually non-existent (got added by mistake when porting from `1.4.7`). On `1.5.2` we have AdvPowerManagement's own `Adjustable Transformer`.

5. Charged Electrolyzer was implemented to work one way, from left to right, meaning the input is always in the left slot. Both charge and discharge recipes. 
IC2's Electrolyzer is hardcoded to have only one recipe. My implementation allows for custom recipes. This is the intended behaviour.
![image](https://github.com/user-attachments/assets/3dc8176c-cd9d-4de0-941d-679f13eed9fa)

Will be fixed in the next release. Keep an eye on the `Releases` page.

**Closed as completed** 2024-11-24 15:10 UTC
